version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    command: >
      sh -c "python manage.py collectstatic --noinput  && python manage.py makemigrations && python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    hostname: 'ui'

  gateway:
    build: infra
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./backend/core/back_static:/home/app/back_static/
      - ./backend/core/media:/home/app/media/
      - ./frontend/build:/home/app/front/build
